name: PR builder is just a magic

on:
  pull_request:
    branches:
      - hazelcast-patches

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get all the letters, words and paragraphs needed for the spell!
        uses: actions/checkout@v3
      - name: Prepare the cauldron and the wand!
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'
          cache: 'maven'
      - name: Maven, now you do the magic! I enchant you the Bash way!
        run: |
          mvn --batch-mode --update-snapshots install
